name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
        postgres:
            image: postgres:12
            env:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: adminpassword
                POSTGRES_DB: Simple_Bank
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run migrations
      run: make migrate_up

    - name: Run Tests
      run: make test
