name: ci-test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Run Tests
    runs-on: ubuntu-latest

    services:
        postgres:
            image: postgres:12
            env:
                POSTGRES_USER: admin
                POSTGRES_PASSWORD: adminpassword
                POSTGRES_DB: Simple_Bank
            ports:
              - 5432:5432
            options: >-
                --health-cmd pg_isready
                --health-interval 10s
                --health-timeout 5s
                --health-retries 5

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.22'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install golang-migrate
      run: | 
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/

    - name: Run migrations
      run: make migrate_up

    - name: Run Tests
      run: make test
